language: rust
dist: bionic

rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo

before_install:
  - rustup component add rustfmt
  - rustup component add clippy
  - sudo apt-get update
  - sudo apt-get install -y curl gcc libgtk-3-dev qtbase5-dev qtdeclarative5-dev qt5-default

script:
  - cargo test --verbose --all
  - cargo clippy --verbose --all
  - cargo fmt --verbose --all -- --check
